### ISSUE TITLE
Initial `GameState` Implementation

### ISSUE THREAD

**Issue by gilkeidar** [ucsd-cse125-sp24/group3#19]
**Task Description:** Create an initial implementation for the `GameState` class that does the following:

- [ ] Contains a list of all objects in the game instance world
- [ ] Contains an `update()` method that updates the game state from the current tick to the next tick (with a fixed time step between ticks)
- [ ] Can support the simulation of object(s) moving through a 3D space
