### ISSUE TITLE
Add Model Loading to Server + Encapsulate Object Position

### ISSUE THREAD

**Issue by gilkeidar** [ucsd-cse125-sp24/group3#90]
**Task Description:**

- [ ] Update `ServerGameState` to read object models and populate a list of `Model`s (with the model size information).
- [ ] Add a `Model` struct to the server that maintains model dimension info
- [ ] Add a `ModelType` enum that maps each model to a particular `Model` (?)
- [ ] Add a `ModelType` or `Model` field to `Object` and `SharedObject`
    - [ ] Encapsulate Physics position + collider position + model dimension into single setters and getters in the `Object` class (i.e., to update object position, must set it via getters / setters to avoid forgetting to set a part of the object position correctly)
